# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 140, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lcd_ymno = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_ymno.setGeometry(QtCore.QRect(300, 120, 64, 23))
        self.lcd_ymno.setObjectName("lcd_ymno")
        self.lcd_minys = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_minys.setGeometry(QtCore.QRect(300, 80, 64, 23))
        self.lcd_minys.setObjectName("lcd_minys")
        self.lcd_delenie = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_delenie.setGeometry(QtCore.QRect(300, 160, 64, 23))
        self.lcd_delenie.setObjectName("lcd_delenie")
        self.lcd_summ = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_summ.setGeometry(QtCore.QRect(300, 40, 64, 23))
        self.lcd_summ.setObjectName("lcd_summ")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 90, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 120, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 160, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 40, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 111, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "->"))
        self.label.setText(_translate("MainWindow", "Разность:"))
        self.label_2.setText(_translate("MainWindow", "Произведение:"))
        self.label_3.setText(_translate("MainWindow", "Частное:"))
        self.label_4.setText(_translate("MainWindow", "Сумма:"))
        self.label_5.setText(_translate("MainWindow", "Второе число(целое)"))
        self.label_6.setText(_translate("MainWindow", "Первое число(целое)"))
